from app.xray.cascade_keys import (
    CASCADE_DEFAULT_FINGERPRINT,
    CASCADE_DEFAULT_SNI,
    CASCADE_INBOUND_PORT,
    generate_cascade_params,
)

FAKE = {"private_key": "PRIV", "public_key": "PUB"}


def test_params_have_all_fields_with_injected_keypair():
    p = generate_cascade_params(keypair=FAKE, uuid_str="u-1", short_id="abcd1234")
    assert p == {
        "port": CASCADE_INBOUND_PORT,
        "uuid": "u-1",
        "private_key": "PRIV",
        "public_key": "PUB",
        "short_id": "abcd1234",
        "sni": CASCADE_DEFAULT_SNI,
        "dest": f"{CASCADE_DEFAULT_SNI}:443",
        "fingerprint": CASCADE_DEFAULT_FINGERPRINT,
    }


def test_uuid_and_short_id_autogenerated_and_unique():
    a = generate_cascade_params(keypair=FAKE)
    b = generate_cascade_params(keypair=FAKE)
    assert a["uuid"] != b["uuid"]
    assert a["short_id"] != b["short_id"]
    assert len(a["short_id"]) == 16  # token_hex(8) → 16 hex-символов
